name: Code Quality

on:
  pull_request:
    branches: "main"
  push:
    branches: "main"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Format with black
      run: |
        black --check --diff src/lorenz_attractor tests/

    - name: Sort imports with isort
      run: |
        isort --check-only --diff src/lorenz_attractor tests/

    - name: Lint with flake8
      run: |
        flake8 src/lorenz_attractor tests/

    - name: Type check with mypy
      run: |
        mypy src/lorenz_attractor --strict --ignore-missing-imports

    - name: Security check with bandit
      run: |
        bandit -r src/lorenz_attractor/ -f json -o bandit-report.json || true
        bandit -r src/lorenz_attractor/ || true

    - name: Check for vulnerabilities with safety
      run: |
        safety check || true